#!/bin/bash

#___________________________________________________
#
# PARAMETROS RECIBIDOS DESDE EL CLIENTE:
# $1 Número de disco
# $2 Número de particion
# $3 Nombre canónico de la imagen (sin extensión)
# $4 Dirección del repositorio (REPO, por defecto)
#___________________________________________________

# Registro de ejecución
echo $* >> $OGLOGFILE

# Solo ejecutable por OpenGnSys Client.
PATH=$PATH:$(dirname $0)
PROG=$(basename $0)
CALLER=$(ogGetCaller)
if [ "$CALLER" != "ogAdmClient" ]; then
	ogRaiseError $OG_ERR_NOTEXEC "$CALLER -> $PROG"
	exit $?
fi

# Valor por defecto para el repositorio.
REPO=${4:-"repo"}

# Si cleinte no está en modo "admin"; activar repositorio para escritura,
#    crear imagen y activar para lectura.
[ "$boot" != "admin" ] && CambiarAcceso admin
if [ -f createImage$ogengine ]; then
	createImage$ogengine "$1" "$2" "$REPO" "$3" &>> $OGLOGFILE
else
	createImage "$1" "$2" "$REPO" "$3" &>> $OGLOGFILE
fi
RETVAL=$?
[ "$boot" != "admin" ] && CambiarAcceso user
exit $RETVAL

