#!/bin/bash
TIME1=$SECONDS


#Load engine configurator from engine.cfg file.
#Carga el configurador del engine desde el fichero engine.cfg
[ -z $OGENGINECONFIGURATE ] && source /opt/opengnsys/etc/engine.cfg

# Clear temporary file used as log track by httpdlog
# Limpia los ficheros temporales usados como log de seguimiento para httpdlog
echo -n "" > $OGLOGSESSION; echo -n  "" > $OGLOGCOMMAND

# Registro de inicio de ejecución
ogEcho log session "$MSG_INTERFACE_START $0 $*"

echo -e "\n Instrucciones a ejecutar: *****************************" >>  $OGLOGFILE
cat  $1 >> $OGLOGFILE


echo -e "\n Salida de las instrucciones: *****************************" >>  $OGLOGFILE
chmod +x $1
# Si mandamos la salida a OGLOGCOMMAND reescribimos lo que manda el comando.
#$1 &>> $OGLOGCOMMAND
$1
RETVAL=$?



TIME=$[SECONDS-TIME1]
if [ $RETVAL == 0 ]
then
	ogEcho log session "[100] Duracion de la operacion $[TIME/60]m $[TIME%60]s"
else
	ogEcho log session "ERROR: operacion no realizada"
fi


# Registro de fin de ejecución
ogEcho log session "$MSG_INTERFACE_END $RETVAL"


exit $RETVAL

