#!/bin/bash

echo -e >>  $OGLOGFILE
echo "Contenido de la ejecucion: *****************************" >>  $OGLOGFILE
cat  $1 >> $OGLOGFILE
echo -e >>  $OGLOGFILE
echo -e >>  $OGLOGFILE
echo "Salida: *****************************" >>  $OGLOGFILE
chmod +x $1
$1 &>> $OGLOGFILE || exit $?
