#!/bin/bash
TIME1=$SECONDS


#Load engine configurator from engine.cfg file.
#Carga el configurador del engine desde el fichero engine.cfg
[ -z $OGENGINECONFIGURATE ] && source /opt/opengnsys/etc/engine.cfg

# Clear temporary file used as log track by httpdlog
# Limpia los ficheros temporales usados como log de seguimiento para httpdlog
echo -n "" > $OGLOGSESSION; echo -n  "" > $OGLOGCOMMAND

# Registro de inicio de ejecución
echo "$MSG_INTERFACE_START $0 $*" | tee -a $OGLOGSESSION $OGLOGFILE

echo -e "\n Instrucciones a ejecutar: *****************************" >>  $OGLOGFILE
cat  $1 >> $OGLOGFILE


echo -e "\n Salida de las instrucciones: *****************************" >>  $OGLOGFILE
chmod +x $1
# Si mandamos la salida a OGLOGCOMMAND reescribimos lo que manda el comando.
#$1 &>> $OGLOGCOMMAND
$1
RETVAL=$?



TIME=$[SECONDS-TIME1]
if [ $RETVAL == 0 ]
then
	echo "[100] Duracion de la operacion $[TIME/60]m $[TIME%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
else
	echo "ERROR no operacion no realizada" | tee -a $OGLOGSESSION $OGLOGFILE
fi


# Registro de fin de ejecución
echo "$MSG_INTERFACE_END $RETVAL" | tee -a $OGLOGSESSION $OGLOGFILE



exit $RETVAL
