#!/bin/bash

#_______________________________________________________________________________________________________________________________
#
# Formato de salida:
# par=Número de particion\tcod=Código de partición\tsfi=Sistema de ficheros\tsoi=Sistema instalado\ttam=Tamaño de la partición\n
#_______________________________________________________________________________________________________________________________

particiones=$(ogGetPartitionsNumber 1)    # Incluir todas las particiones
cfg="0::::$(ogGetDiskSize 1);"            # e información de disco (partición 0)

for ((par=1;par<=$particiones;par++)); do
	# Código del identificador de tipo de partición
	cod=$(ogGetPartitionId 1 $par)
	# Tipo de partición o sistema de fichero
	fsi=$(getFsType 1 $par 2>/dev/null)
	fsi=${fsi:-"EMPTY"}
	# Tamaño de la particón
	tam=$(ogGetPartitionSize 1 $par 2>/dev/null)
	tam=${tam:-"0"}
	# Sistema de fichero instalado 
	if [ $cod == 82 ]; then
		soi=" "
	else
		soi=$(getOsVersion 1 $par 2>/dev/null | cut -f2 -d:)
   	fi	

	cfg="$cfg$par:$cod:$fsi:$soi:$tam;"
done

echo $cfg | awk '{
		n=split($0,sep,";");
		for (i=1; i<n; i++){
			split (sep[i],dua,":");
		 	printf ("par=%s\tcpt=%s\tfsi=%s\tsoi=%s\ttam=%s\n",
					dua[1],dua[2],dua[3],dua[4],dua[5]);
			}
		}'


