#!/bin/bash
# Nombre:       HidraOSVersion
# Descripcion:  Muestra tipo y version de SO de la particion seleccionada.
# Formato:      hidraOSVersion ndisco nparticion
# Salida:       tipo:version
# 	tipo : ( Linux, Windows )
# Error:        1 - mal formato de ejecucion.
#               2 - no existe el fichero de dispositivo.
#		3 - fallo al montar la particion		
# Requisitos:   awk, head, hidraMount, hidraTypeFS, hidraGetRegistryKey
# Notas:        Solo ejecutable por root
# Licencia:	GNU GPL
# Version:      1.0 - Detecta Linux y Windows, no existe equivalente en EAC.
# Autor:        Ramon Gomez - ETSII, Univ. Sevilla
# Fecha:        27/03/2009

source  $(dirname $0)/hidraEnviron

# Error si no se reciben 2 parametros.
[ $# != 2 ] && exit $ERRFORMAT

# Montar la particion, si no lo estaba previamente.
DIRMONT=$(hidraMount $1 $2) || exit $?
#trap "hidraUnmount $DIRMONT" 1 2 3 6	### NO disponible aun
trap "hidraUnmount $1 $2" 1 2 3 6

case "$(hidraTypeFS $1 $2)" in
    EXT[234] | REISERFS | REISER4)
	TIPO="Linux"
	# Leer descripcion del sistema Linux.
	VERSION=$(chroot $DIRMONT lsb_release -d 2>/dev/null| awk -F: '{gsub (/\t/,""); print $2}')
	# Si no se puede obtener, buscar en ficheros del sistema.
	if [ -z "$VERSION" ]; then
 	    UBUNTU="$DIRMONT/etc/lsb-release" 
 	    [ -e $UBUNTU ] && VERSION="$(awk 'BEGIN {FS="="}; $1~/DESCRIPTION/ {gsub(/\"/,"",$2); print $2}' $UBUNTU)"
 	    REDHAT="$DIRMONT/etc/redhat-release" 
	    [ -e $REDHAT ] && VERSION="$(head -1 $REDHAT)" 
 	    SUSE="$DIRMONT/etc/SuSE-release" 
	    [ -e $SUSE ] && VERSION="$(head -1 $SUSE)" 
	fi
	[ -e $DIRMONT/lib64 ] && VERSION="$VERSION 64 bits"
	;;
    NTFS | HTNFS | FAT32 | HFAT32)
	TIPO="Windows"
	# Leer la version del registro de Windows.
	VERSION=$(hidraGetRegistryKey $DIRMONT software '\Microsoft\Windows NT\CurrentVersion\ProductName')
	;;
esac

# Mostrar resultado y salir sin errores.
[ -n "$VERSION" ] && echo "$TIPO:$VERSION"
exit 0

