#!/bin/bash
# Nombre:	hidraHardwareInfo
# Descripcion:	Recopila información del inventario hardware del PC.
# Formato:	hidraHardwareInfo
# Salida:	TipoDispositivo:Modelo
#	TipoDispositivo = { bio, boa, cdr, cpu, dis, fir, mem, mod, mul,
#			    net, ser, vga }
# Error:	No
# Requisitos:	lshw, awk
# Notas:	Solo ejecutable por root
# Version:	1.0 - No compatible con EAC (probar el fichero de inventario,
#			EAC incluye nuevos comandos de deteccion de hardware).
# Autor:	Ramoon oómez, ETSII Univ. Sevilla
# Fecha:	18/03/2009
# Version:	1.1 - Usa lshw con todos los datos en vez del fichero de 
#			inventario de EAC.
# Autor:	Ramoon oómez, ETSII Univ. Sevilla
# Fecha:	23/04/2009


# Recopilacion de disposibivos procesando la salida de lshw.
lshw | awk 'BEGIN {tipo="mod";}
	/product:/ {sub(/ *product: */,"");  prod=$0;}
	/vendor:/  {sub(/ *vendor: */,"");   vend=$0;}
	/version:/ {sub(/ *version: */,"v.");vers=$0;}
	/size:/    {sub(/ *size: */,"");     size=$0;}
	/\*-/	   {if (tipo=="mem")
			print tipo"="size;
		    else
			if (tipo!="" && prod!="")
			    print tipo"="vend,prod,size,vers;
		    tipo=prod=vend=vers=size="";}
	/-core/    {tipo="boa";}
	/-firmware/ {tipo="bio";}
	/-cpu/     {tipo="cpu";}
	/-memory/  {tipo="mem";}
	/-disk/    {tipo="dis";}
	/-cdrom/   {tipo="cdr";}
	/-display/ {tipo="vga";}
	/-network/ {tipo="net";}
	/-multimedia/ {tipo="mul";}
	/-usb/     {tipo="usb";}
	/-firewire/ {tipo="fir";}
	/-serial/  {tipo="ser";}
	END 	   {if (tipo!="" && prod!="")
			print tipo"="vend,prod,size,vers;}
      ' $FICH

exit


### CODIGO ANTIGUO ###
source $(dirname $0)/hidraEnviron

# Tipo de CPU
awk -F: '/model name/ {print "cpu="$2;}' /proc/cpuinfo 2>/dev/null
# Cantidad de memoria
awk -F: '/MemTotal:/ {print "mem="$2/1024" MB";}' /proc/meminfo 2>/dev/null
# Discos internos
for d in $(hidraDisk); do 
    parted -s $d print | \
	awk -F: '/Model/	{m=$2;}
		 /^Disk/	{d=$2;}
		 END { printf "dis=%s %s\n",m,d; }
		'
done
# Tarjeta de sonido
awk -F: '{if ($2!="") print "aud="$2;}' /proc/asound/cards 2>/dev/null
# Tarjetas PCI (códigos y driver)
# - Clase 2xx: red
# - Clase 3xx: vídeo
for pci in /sys/bus/pci/devices/*; do
    awk -F= '	$1~/PCI_CLASS/	{if ($2~/^2/) c="net";
				 if ($2~/^3/) c="vga";}
		$1~/PCI_ID/	{i=$2}
	    END {if (c!="") 
		    printf ("%s=%s\n",c,tolower(i));
	}' $pci/uevent 2>/dev/null
done
