#!/bin/bash
# Nombre:	hidraDeletePartitionTable
# Descripcion:	Genera una nueva tabla de particiones vacia para un disco.
# Formato:	hidraDeletePartitionTable numdisco
# Salida:	Ninguna (por determinar)
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
# Requisitos:	hidraDisk, DeletePartitionTable (EAC)
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatible con EAC: llama a la funcion DeletePartitionTable
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	30/03/2009

source $(dirname $0)/hidraEnviron

# Error si no se recibe 1 parametro
[ $# -ne 1 ] && exit 1

# Sustituye num. de disco por el dispositivo.
DISCO="$(hidraDisk $1)" || exit $?

DeletePartitionTable $DISCO
