#!/bin/bash
# Nombre:	hidraFormatCache
# Descripcion:	Muestra el dispositivo de la particion definida como cahce.
# Formato:	hidraFormatCache
# Salida:	Ninguna (por determinar).
# Error:	(definidos por EAC)
#		2 - Dispositivo no encontrado (cache no definido).
# Requisitos:	FormatCACHE (EAC)
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatibilidad Con EAC: llama a la funcion FormatCACHE
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	30/03/2009

source $(dirname $0)/hidraEnviron

# Error si no se encuentra particion de cache.
FindCache $* || exit $ERRNOTFOUND

FormatCACHE $*
