#!/bin/bash
# Nombre:	hidraFSIndex
# Descripcion:	Genera el indice de ficheros de un sistema de archivos.
# Formato:	hidraFSIndex numdisco numparticion
# Salida:	salida de mkfs (por determinar)
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
#		3 - tipo de particion desconocido o no formateable.
# Requisitos:	ls, hidraMount
# Notas:	Solo ejecutable por root
# Version:	1.0 - Version inicial: intento inicial para crear diferenciales.
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	07/05/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 2 parametros.
[ $# -ne 2 ] && exit $ERRFORMAT

# Sustituye num. de disco por el dispositivo.
PART="$(hidraDisk $1 $2)" || exit $?

# Procesar segun el tipo de sistema de archivos.
case "$(hidraTypeFS $1 $2)" in
    NTFS|HNTFS)
	ntfsls -Ralfs $PART
	;;
    EXT[234]|REISERFS|REISER4|BIGDOS|HBIGDOS)
	# Error si no se puede montar la particion.
	DIR="$(hidraMount $1 $2)" || exit $?
	cd $DIR
#	ls -RAQln
	find . -ls
	;;
    *) 	exit $ERRPARTITION;;
esac

