#!/bin/bash
# Nombre:       hidraGetRegistryKey
# Descripcion:  Devuelve el valor de una clave del registro de Windows.
# Formato:      hidraGetRegistryKey puntomontaje tiporegistro clave
#	tiporegistro: { default, sam, security, software, system, components }
# Salida:       ValorClave
# Error:        1 - mal formato de ejecución.
#		2 - no existe el fichero.
# Requisitos:   drbl-chntpw, awk, hidraPath
# Notas:        Solo ejecutable por root
#		La particion de Windows debe estar montada previamente.
# Version:      1.0 - Version inicial: No existe equivalente en EAC.
# Autor:        Ramon Gomez - ETSII, Univ. Sevilla
# Fecha:        27/03/2009

source  $(dirname $0)/hidraEnviron

# Error si no se reciben 3 parametros.
[ $# != 3 ] && exit $ERRFORMAT

# Camino del fichero de registro en NT/2000.
FICHNT=$(hidraPath "/$1/winnt/system32/config/$2")
[ -f $FICHNT ] && FICH="$FICHNT" 
# Camino del fichero de registro en XP/Vista.
FICHXP=$(hidraPath "/$1/windows/system32/config/$2")
[ -f $FICHXP ] && FICH="$FICHXP" 
[ ! -f $FICH ] && exit $ERRNOTFOUND

# Cambiar a la carpeta adecuada evita recortes de "chntpw".
# Devolver la clave de registro.
drbl-chntpw $FICH <<<"
cd ${3%\\*}
cat ${3##*\\}
q" 2>/dev/null | awk '/> Value/ {getline;print $0;}'

