#!/bin/bash
# Nombre:       hidraListRegistryKeys
# Descripcion:  Lista el contenido de una clave del registro de Windows.
# Formato:      hidraListRegistryKeys puntomontaje tiporegistro clave
#	tiporegistro: { default, sam, security, software, system, components }
# Salida:       (ninguna, por determinar)
# Error:        1 - mal formato de ejecución.
#               2 - no existe el fichero o la clave del registro.
# Requisitos:   drbl-chntpw, hidraPath
# Notas:        Solo ejecutable por root
#		La particion de Windows debe estar montada previamente.
# Version:      1.0 - version inicial.
# Autor:        Ramon Gomez - ETSII, Univ. Sevilla
# Fecha:        30/03/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 3 parametros.
[ $# != 3 ] && exit $ERRFORMAT

# Camino del fichero de registro en NT/2000.
FICHNT=$(hidraPath "/$1/winnt/system32/config/$2")
[ -f $FICHNT ] && FICH="$FICHNT" 
# Camino del fichero de registro en XP/Vista.
FICHXP=$(hidraPath "/$1/windows/system32/config/$2")
[ -f $FICHXP ] && FICH="$FICHXP" 
[ ! -f $FICH ] && exit $ERRNOTFOUND

# Lee el contenido de la clave del registro (elimina info. innecesaria).
drbl-chntpw $FICH <<<"
ls $3
q" 2>/dev/null | awk 'BEGIN {FS="[<>]"} $1~/^\[[0-9a-f]*\]  / {print $2}'

