#!/bin/bash
# Nombre:	hidraDeleteFile
# Descripcion:	Borra un fichero.
# Formato:	hidraDeleteFile numdisco numpart camino
# Salida:	Ninguna (por determinar).
# Error:        1 - mal formato de ejecución.
#		2 - no existe el fichero.
# Requisitos:	hidraPath, hidraMount
# Notas:	Solo ejecutable por root
#		Solo borra ficheros de una particion, definir si se usara para borrar 
#			de cache o del repositorio del servidor.
# Version:	1.0 - Compatibilidad Con EAC: nueva funcion
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	30/03/2009

source $(dirname $0)/hidraEnviron

FICH="$(hidraPath $(hidraMount $1 $2)/$3)" || exit $?

[ ! -f $FICH ] && exit $ERRNOTFOUND
rm $FICH
