#!/bin/bash
# Nombre:	hidraEACServerIP
# Descripcion:	Devuelve la direccion IP del servidor principal EAC.
# Formato:	hidraEACServertIP
# Salida:	ip (por determinar).
# Error:	(definido por EAC)
# Requisitos:	Variable IPservidor (EAC)
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatibilidad Con EAC: muestra la variable IPservidor.
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	31/03/2009

source $(dirname $0)/hidraEnviron

echo $IPservidor
