#!/bin/bash
# Nombre:	hidraLinuxBootParametes
# Descripcion:	Obtiene de GRUB los parametros de arranque para Linux.
# Formato:	hidraLinuxBootParameters numdisco numparticion
# Salida:	kernel initrd "parametroskernel"
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
#		3 - tipo de particion desconocido o no se puede montar.
#		4 - fichero no encontrado.
# Requisitos:	hidraMount
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatibilidad Con EAC: soluciona problemas de HDBoot
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	02/04/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 2 parametros.
[ $# -ne 2 ] && exit 1

# Obtiene el punto de montaje de la particion.
MONT="$(hidraMount $1 $2)" || exit $?

# Fichero de configuracion de GRUB.
CONF=$MONT/boot/grub/menu.lst
[ ! -f $CONF ] && exit 4

# Toma del fichero de configuracion los valores del kernel, initrd
#    y parametros de arranque usando las clausulas por defecto, y
#    los formatea para que sean compatibles con kexec.
awk 'BEGIN {cont=-1;}
     $1~/^default/	{def=$2}
     $1~/^title/	{cont++}
     $1~/^kernel/	{if (def==cont) {
			    kern=$2;
			    sub($1,"");sub($1,"");sub(/^[ \t]*/,"");app=$0}
			}
     $1~/^initrd/	{if (def==cont) init=$2}
     END {if (kern!="") printf("%s %s %s", kern,init,app)}
    ' $CONF
