#!/bin/bash
# Nombre:	hidraSetPartitionType
# Descripcion:	Asigna el tipo a una determinada particion.
# Formato:	hidraSetPartitionType numdisco numparticion mnemonico
# Salida:	Ninguna (por determinar)
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
# Requisitos:	sfdisk, hidraDisk
# Notas:	Solo ejecutable por root
#		Queda definir formato para atributos (arranque, oculta, ...).
# Version:	1.0 - Compatible con EAC: sustituye a la funcion SetPartitionType
#			Controla más tipos de particones.
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	30/03/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 3 parametros
[ $# -ne 3 ] && exit $ERRFORMAT

# Comprobar que existe la particion.
DISCO="$(hidraDisk $1)" || exit $?
PART="$(hidraDisk $1 $2)" || exit $?

# Identificador de tipo de particion.
case "$3" in
     EMPTY)	 ID=0  ;;
     EXTENDED)	 ID=5  ;;
     NTFS)	 ID=7  ;;
     HNTFS)	 ID=17 ;;
     FAT32)	 ID=b  ;;
     HFAT32)	 ID=1b ;;
     BIGDOS)	 ID=6  ;;
     HBIGDOS)	 ID=16 ;;
     EXT[234])	 ID=83 ;;
     LINUX-SWAP) ID=82 ;;
     LINUX-LVM)	 ID=8e ;;
     CACHE)	 ID=a7 ;;
     RAID-EXT[234]) ID=fd ;;
     *)		 exit 3;;
esac

# Modificar la particion.
sfdisk --change-id $DISCO $2 $ID >/dev/null 2>&1

