#!/bin/bash
# Nombre:	hidraMountCache
# Descripcion:	Monta la particion de cache y devuelve el punto de montaje
# Formato:	hidraMountCache
# Salida:	Ninguna (por determinar).
# Error:	(definido por EAC)
# Requisitos:	MountCache (EAC)
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatibilidad Con EAC: llama a la funcion MountCache
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	30/03/2009

source $(dirname $0)/hidraEnviron

MountCache
