#!/bin/bash
# Nombre:	hidraEnviron
# Descripcion:	Define las variables del entorno de trabajo de Hidra.
# Formato:	source hidraEnviron
# Notas:	Solo ejecutable por root
# Licencia:	GNU GPL
# Version:	1.0 - Version inicial compatible con EAC
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	26/03/2009

# Directorios de EAC y de HIDRA.
REPO=${REPO:-"/var/EAC"}
HIDRADIR=${HIDRADIR:-"$REPO/hidra"}

# Funciones EAC
if ! typeset -F Disk >/dev/null; then
    if [ -d $REPO/admin/librerias ]; then
	for i in $REPO/admin/librerias/*.lib; do
	    source $i
	done
	# Caminos de busqueda de procedimientos EAC.
	[ -z "$(echo $PATH|grep $REPO/admin)" ] && PATH=$PATH:$REPO/admin/procedimientos
    fi
fi

# Mnemonicos de errores Hidra.
if [ -z "$ERRFORMAT" ]; then
    declare -ir ERRFORMAT=1	# Formato de ejecucion incorrecto.
    declare -ir ERRNOTFOUND=2	# Fichero o dispositivo no encontrado.
    declare -ir ERRPARTITION=3	# Error en particion de disco.
    declare -ir ERRNOTEXEC=4	# Programa o funcion no ejecutable.
    declare -ir ERRNOTOS=5	# Sin sistema operativo.
    # Caminos de busqueda de comandos Hidra.
    [ -z "$(echo $PATH|grep $HIDRADIR)" ] && PATH=$PATH:$HIDRADIR/scripts
fi

export PATH HIDRADIR

