#!/bin/bash
# Nombre:	hidraCreateLogicalPartitions
# Descripcion:	Asigna las particiones logicas de la particion extendida.
# Formato:	hidraCreateLogicalPartitions numdisco tipopart1:tamañoKB1 ...
# Salida:	salida de sfdisk (por determinar)
# 	tipopart = { FAT32, HFAT32, NTFS, HNTFS EXT2, EXT3, EXT4, LINUX-SWAP,
#		     EMPTY }
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
#		3 - error en formato o tipo de particion extendida.
# Requisitos:	sfdisk, partprobe, grep, awk, hidraDisk, hidraUnmountAll
# Notas:	Solo ejecutable por root
#		Queda definir formato para atributos (arranque, oculta, ...).
# Version:	1.0 - Compatible con EAC: sustituye parcialmente a la funcion CreatePartitions
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	27/03/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben entre 2 y 5 parametros
[ $# -lt 2 -o $# -gt 5 ] && exit $ERRFORMAT

# Sustituye num. de disco por el dispositivo.
DISCO="$(hidraDisk $1)" || echo $?
shift

# Fichero temporal de entrada para "sfdisk"
tmpsfdisk=/tmp/sfdisk$$
trap "rm -f $tmpsfdisk" HUP INT QUIT ABRT TERM

# Recuperar las 4 particiones primarias
echo "unit: sectors" >$tmpsfdisk
echo                >>$tmpsfdisk
sfdisk -d $DISCO | grep -e "$DISCO[1-4]" >>$tmpsfdisk

# Sector inicial y num. total de sectores para particiones logicas (a partir de la 5).
DATOSEXT=$(awk 'BEGIN {FS="[:=,]"} { if ($7==" 5") {printf "%d:%d",$3,$5} }' $tmpsfdisk)
SECTOR="${DATOSEXT%:*}"
[ -z "$SECTOR" ] && exit $ERRPARTITION
NSECTORES="$[SECTOR+${DATOSEXT#*:}]"
[ "$NSECTORES" = "$SECTOR" ] && exit $ERRPARTITION
PART=5

# Terminar de generar fichero temporal para "sfdisk".
while [ $# != 0 ]; do
	# Formato de cada parametro - Tipo:Tamanyo
	TIPO="${1%%:*}"
	TAM="${1#*:}"
	[ -z "$TAM" ] && exit $ERRFORMAT
	# Convertir en sectores de 512 B.
	TAM=$[TAM*2]
	[ $TAM -eq 0 ] && exit $ERRFORMAT
	# Identificador de tipo de particion.
	case "$TIPO" in
	     EMPTY)	 ID=0  ;;
	     NTFS)	 ID=7  ;;
	     HNTFS)	 ID=17 ;;
	     FAT32)	 ID=b  ;;
	     HFAT32)	 ID=1b ;;
	     EXT[234]|REISERFS|REISER4)
			 ID=83 ;;
	     LINUX-SWAP) ID=82 ;;
	     *)		 exit $ERRFORMAT;;
	esac
	echo "$DISCO$PART : start=$SECTOR, size=$TAM, Id=$ID" >>$tmpsfdisk
	SECTOR=$[SECTOR+TAM]
	# Error si se supera el num. total de sectores.
	[ $SECTOR -gt $NSECTORES ] && exit $ERRFORMAT
	PART=$[PART+1]
	shift
done

# Desmontar todos los sistemas de archivos del disco.
hidraUnmountAll $1
# Definir particiones y notificar al kernel.
sfdisk -f $DISCO < $tmpsfdisk 2>/dev/null && partprobe
rm $tmpsfdisk
