#!/bin/bash
# Nombre:	hidraUnmount
# Descripcion:	Desmonta una particion local.
# Formato:	hidraUnmount numdisco numparticion
# Salida:	(ninguna)
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
# Requisitos:	hidraDisk, UmountPartition (EAC)
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatibilidad Con EAC: llama a la funcion UmountPartition.
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	25/03/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 2 parametros.
[ $# -ne 2 ] && exit $ERRFORMAT

# Sustituye num. de disco por el dispositivo.
PART="$(hidraDisk $1 $2)" || exit $?

# NOTAS: no se comprueba previamente el tipo de particion, la funcion UmountPartition no devuelve errores.
UmountPartition $* >/dev/null

