#!/bin/bash
# Nombre:	hidraBoot
# Descripcion:	Arranca el sistema operativo de la particion indicada.
# Formato:	hidraBoot numdisco numparticion
# Salida:	Directorio del punto de montaje.
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
#		3 - tipo de particion desconocido o no se puede montar.
# Requisitos:	hidraDisk, hidraTypeFS, HDBoot (EAC)
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatibilidad Con EAC: llama a la funcion HDBoot
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	27/03/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 2 parametros.
[ $# -ne 2 ] && exit 1

# Sustituye num. de disco por el dispositivo.
PART="$(hidraDisk $1 $2)" || exit $?

# NOTAS: no se comprueba previamente el tipo de particion, ni si hay sistema operativo, la funcion HDBoot no devuelve errores.
HDBoot $*

