#!/bin/bash
# Nombre:       WindowsSoftware
# Descripcion:  Muestra los programas instalados en Windows.
# Formato:      WindowsSoftware numdisco numparticion
# Salida:       Lineas con el formato (una por aplicacion):
#		Programa Version
# Error:        1 - mal formato de ejecución.
#               2 - no existe el fichero de dispositivo.
#		3 - fallo al montar la particion		
# Requisitos:   chntpw, awk, sort, uniq, hidraGetRegistryKey
# Notas:        Solo ejecutable por root
# Version:      1.0 - Version inicial.
# Autor:        Ramon Gomez - ETSII, Univ. Sevilla
# Fecha:        30/03/2008

source $(dirname $0)/hidraEnviron

# Error si no se reciben 2 parametros.
[ $# != 2 ] && exit 1

# Montar particion.
DIRMONT=$(hidraMount $1 $2) || exit $?

trap "hidraUnmount $DIRMONT" 1 2 3 6

# Claves de registro para programas instalados: formato "{clave}".
#CLAVES=$(ListarClaveRegistro $DIRMONT software '\Microsoft\Windows\CurrentVersion\Uninstall' | grep "{.*}")
CLAVES=$(hidraListRegistryKeys $DIRMONT software '\Microsoft\Windows\CurrentVersion\Uninstall')
#CLAVES=$(chntpw $(CaminoWindows $DIRMONT/windows/system32/config/software) <<< '
#ls \Microsoft\Windows\CurrentVersion\Uninstall
#q' | awk 'BEGIN {FS="[<>]"}
#	  $2~/\{.*\}/ {printf "'%s' ",$2}')

# Mostrar los valores "DisplayName" y "DisplayVersion" para cada clave.
(for i in $CLAVES; do
    PROG=$(hidraGetRegistryKey $DIRMONT software "\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\$i\\DisplayName")
    if [ -n "$PROG" ]; then
	VERS=$(hidraGetRegistryKey $DIRMONT software "\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\$i\\DisplayVersion")
	echo "$PROG $VERS"
    fi
done) | sort | uniq

