#!/bin/bash
# Nombre:	hidraMountRepo
# Descripcion:	Monta un repositorio alternaivo y devuelve el punto de montaje
# Formato:	hidraMountRempo iprepo
# Salida:	Punto de montaje (por determinar).
# Error:	(definido por EAC)
# Requisitos:	MountRepo (EAC)
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatibilidad Con EAC: llama a la funcion MountCache
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	20/04/2009

source $(dirname $0)/hidraEnviron

MountRepo $*
