#!/bin/bash
# Nombre:	hidraClientIP
# Descripcion:	Devuelve la direccion IP del cliente.
# Formato:	hidraClientIP
# Salida:	ip (por determinar).
# Error:	(definido por EAC)
# Requisitos:	Variable IP (EAC)
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatibilidad Con EAC: muestra la variable IP.
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	31/03/2009

source $(dirname $0)/hidraEnviron

echo $IP
