#!/bin/bash
# Nombre:	hidraFindCache
# Descripcion:	Muestra el dispositivo de la particion definida como cahce.
# Formato:	hidraFindCache
# Salida:	Ninguna (por determinar).
# Error:	1 - sin cache (definido por EAC)
# Requisitos:	FindCache (EAC)
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatibilidad Con EAC: llama a la funcion FindCache
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	30/03/2009

source $(dirname $0)/hidraEnviron

FindCache
