#!/bin/bash
# Nombre:	hidraFSReduce
# Descripcion:	Reduce el tamano del sistema de archivos (al minimo + 1 MB).
# Formato:	hidraFSReduce numdisco numparticion
# Salida:	Tamano reducido en KB.
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
#		3 - tipo de particion desconocido o no formateable.
# Requisitos:	*resize*, hidraTypeFS, hidraUnmount
# Notas:	Solo ejecutable por root
#		Puede ser interesante usar la funcion para ampliar y reducir.
# Version:	1.0 - Version inicial: sustituye a la funcion ReducirFileSystemNT.
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	24/04/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 2 parametros.
[ $# != 2 ] && exit $ERRFORMAT

# Sustituye num. de particion por el dispositivo.
PART="$(hidraDisk $1 $2)" || exit $?

# Redimensionar segun el tipo de particion.
case "$(hidraTypeFS $1 $2)" in
     EXT[234])
	hidraUnmount $1 $2
	# Tamano de los bloques del sistema de archivos
	BLKS=$(tune2fs -l $PART | awk '/Block size/ {print int($3/512)}')	
	# Traduce el num. en sectores de 512B a tamano en MB.
	TAM=$(resize2fs -P $PART | \
		awk -v B=$BLKS '/minimum size/ {print int($7*B/2048+1000)}')	
	resize2fs -fp $PART "${TAM}M" >/dev/null || exit $ERRPARTITION
	;;
     REISERFS)		# Usar "resize_reiserfs"
	;;
     NTFS|HNTFS)
	hidraDeleteFile $1 $2 pagefile.sys
	hidraUnmount $1 $2
	# Obtiene tamano minimo en MB.
	TAM=$(ntfsresize -fi $PART | awk '/resize at/ {print $8+1000}')
	ntfsresize -fns "${TAM}M" $PART >/dev/null || exit $ERRPARTITION
	ntfsresize -fs "${TAM}M" $PART <<<"y" >/dev/null|| exit $ERRPARTITION
	;;
     *) exit $ERRPARTITION;;
esac
# Mostrar tamano en KB.
echo $[TAM*1024]
