#!/bin/bash
# Nombre:	hidraCreateImageFromPartition
# Descripcion:	Crea una imagen completa de una particion de disco.
# Formato:	hidraCreateImageFromPartition numdisco numparticion iprepo dirbase imagen compresor
# Salida:	(por determinar)
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
#		3 - tipo de particion desconocido o no se puede montar.
#		4 - fichero o programa no accesible
# Requisitos:	hidraUnmount, CreateImageFromPartition (EAC)
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatible con EAC: llama a la funcion CreateImageFromPartition
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	14/04/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 6 parametros.
[ $# -ne 6 ] && exit $ERRFORMAT

# Error si la particion esta bloqueada.
hidraIsLocked $1 $2 && exit $ERRLOCKED

# Desmontar la particion, si estaba montada previamente.
hidraUnmount $1 $2 || exit $?

# ATENCION: la funcion CreateImageFromPartition no comprueba que se genere la
#	 imagen en el directorio exportado por el servidor y la puede crear en
#	 local. El codigo comprueba que el directorio este importado.
DIRIMG=$(ConnectToRepo $IPservidor "$4" / | grep "$d")
if [ "$3" = "$IPservidor" ]; then
    for d in $(showmount -d $IPservidor | grep $REPO); do
	DIR=$DIR$(echo $DIRIMG|grep $d)
    done
    [ -z "$DIR" ] && exit $ERRNOTFOUND
fi

#Bloquear la particion.
hidraLock $1 $2

# Desbloquear la particion y borrar ficheros creados si hay salida de error.
trap "hidraUnlock $1 $2; rm $(ConnectToRepo $3 $4 /)$5.$6-$2{,.mcast,.torrent}" 1 2 3 6 9

# NOTAS: no se comprueba previamente el tipo de particion,
#	 la funcion CreateImageFromPartition no devuelve errores.
CreateImageFromPartition $1 $2 $3 "${4%/}/" "$5.$6"

# Desbloquear la particion.
hidraUnlock $1 $2
