#!/bin/bash
# Nombre:	hidraFSCheck
# Descripcion:	Formatea una particion segun su tipo definido en la tabla del disco.
# Formato:	hidraFSCheck numdisco numparticion
# Salida:	salida de mkfs (por determinar)
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
#		3 - tipo de particion desconocido o no formateable.
# Requisitos:	fsck*, hidraDisk, hidraTypeFS
# Notas:	Solo ejecutable por root
# Version:	1.0 - Version inicial: EAC define pero no usa la funcion FormatParticion
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	01/04/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 2 parametros.
[ $# -ne 2 ] && exit $ERRFORMAT

# Sustituye num. de disco por el dispositivo.
PART="$(hidraDisk $1 $2)" || exit $?

# Elegir tipo de formato segun el tipo de particion.
case "$(hidraTypeFS $1 $2)" in
     EXT2)		TIPO="ext2" ;;
     EXT3)		TIPO="ext3" ;;
     EXT4)		TIPO="ext4" ;;
     REISERFS)		TIPO="reiserfs" ;;
     REISER4)		TIPO="reiser4" ;;
     NTFS|HNTFS)	PROG="ntfsfix" ;;
     FAT32|HFAT32)	TIPO="vfat" ;;
     BIGDOS|HBIGDOS)	TIPO="msdos" ;;
     CACHE)		TIPO="ext3" ;;
     *) 		exit 3;;
esac

# Desmontar la particion antes de comprobarla.
hidraUnmount $1 $2
# Comprobar particion, si no se define programa se usa fsck.
if [ -z "$PROG" ]; then
    fsck -t $TIPO $PART
else
    $PROG $PART
fi

