#!/bin/bash
# Nombre:	hidraFormat
# Descripcion:	Formatea una particion segun su tipo definido en la tabla del disco.
# Formato:	hidraFormat numdisco numparticion [etiqueta]
# Salida:	salida de mkfs (por determinar)
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
#		3 - tipo de particion desconocido o no formateable.
# Requisitos:	mkfs*, hidraDisk, hidraTypeFS
# Notas:	Solo ejecutable por root
#		Puede definirse un parametro para la etiqueta de volumen.
#		Puede ser interesante poner un indicador de forzoso para particion ya formateada.
# Version:	1.0 - Version inicial: EAC define pero no usa la funcion FormatParticion
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	27/03/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 2 parametros.
[ $# -lt 2 -o $# -gt 3 ] && exit $ERRFORMAT

# Sustituye num. de disco por el dispositivo.
DISCO="$(hidraDisk $1)" || exit $?
PART="$(hidraDisk $1 $2)" || exit $?
# Etiquetas de particion.
[ -n "$3" ] && PARAMS="-L $3"

# Elegir tipo de formato segun el tipo de particion.
case "$(hidraTypeFS $1 $2)" in
     EXT2)		TIPO="ext2" ;;
     EXT3)		TIPO="ext3" ;;
     EXT4)		TIPO="ext4" ;;
     REISERFS)		TIPO="reiserfs" ;;
     REISER4)		TIPO="reiser4" ;;
     NTFS|HNTFS)	TIPO="ntfs -f" ;;
     FAT32|HFAT32)	TIPO="vfat" ;;
     BIGDOS|HBIGDOS)	TIPO="msdos" ;;
     CACHE)		TIPO="ext3" ;;
     *) 		exit $ERRPARTITION;;
esac

# Desmontar la particion antes de formatear.
hidraUnmount $1 $2
# Formatear particion.
mkfs -t $TIPO $PARAMS $PART

