#!/bin/bash
# Nombre:	hidraFormat
# Descripcion:	Formatea una particion segun su tipo definido en la tabla del disco.
# Formato:	hidraFormat numdisco numparticion
# Salida:	salida de mkfs (por determinar)
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
#		3 - tipo de particion desconocido o no formateable.
# Requisitos:	mkfs*, hidraDisk, hidraTypeFS
# Notas:	Solo ejecutable por root
#		Puede ser interesante poner un indicador de forzoso para particion ya formateada.
#		Puede definirse un parametro para la etiqueta de volumen.
# Version:	1.0 - Version inicial: EAC define pero no usa la funcion FormatParticion
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	27/03/2009


# Error si no se reciben 2 parametros.
[ $# -ne 2 ] && exit 1

# Sustituye num. de disco por el dispositivo.
DISCO="$(hidraDisk $1)" || exit $?
PART ="$(hidraDisk $1 $2)" || exit $?

# Elegir tipo de formato segun el tipo de particion.
case "$(hidraTypeFS $1 $2)" in
     EXT2)		TIPO="ext2" ;;
     EXT3)		TIPO="ext3" ;;
     EXT4)		TIPO="ext4" ;;
     REISERFS)		TIPO="reiserfs" ;;
     REISER4)		TIPO="reiser4" ;;
     NTFS|HNTFS)	TIPO="ntfs" ;;
     VFAT|HVFAT)	TIPO="vfat" ;;
     BIGDOS|HBIGDOS)	TIPO="msdos" ;;
     CACHE)		TIPO="ext3" ;;
     *) 		exit 3;;
esac

# Formatear particion.
### Modo depuracion, quitar comentarios para trabajar.
#mkfs -t $TIPO $PART
