#!/bin/bash
# Nombre:       hidraSetWindwosName
# Descripcion:  Cambia el nombre del equipo en el registro de Windows.
# Formato:      hidraSetWindowsName ndisco nparticion nombre
# Salida:       (ninguna, por determinar)j
# Error:        1 - mal formato de ejecución.
#               2 - no existe el fichero de dispositivo.
#		3 - fallo al montar la particion		
# Requisitos:   hidraMount, hidraSetRegistryKey
# Notas:        Solo ejecutable por root
# Version:      1.0 - Compatible con EAC: sustituye a la funcion SetWindowsName
# Autor:        Ramon Gomez - ETSII, Univ. Sevilla
# Fecha:        30/03/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 3 parametros.
[ $# != 3 ] && exit 1

# Montar particion.
DIRMONT=$(hidraMount $1 $2) || exit $?

trap "hidraUnmount $DIRMONT" 1 2 3 6

### Modo depuracion, quitar comentarios para trabajar.
# Modificar claves de registro.
hidraSetRegistryKey $DIRMONT system '\ControlSet001\Control\ComputerName\ComputerName\ComputerName' "$3"
hidraSetRegistryKey $DIRMONT system '\ControlSet001\Services\Tcpip\Parameters\Hostname' "$3"
hidraSetRegistryKey $DIRMONT system '\ControlSet001\Services\Tcpip\Parameters\NV Hostname' "$3"

