#!/bin/bash
# Nombre:	hidraClientMAC
# Descripcion:	Devuelve la direccion MAC (Ethernet) del cliente.
# Formato:	hidraClientMAC
# Salida:	mac (por determinar).
# Error:	(definido por EAC)
# Requisitos:	Variable MAC (EAC)
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatibilidad Con EAC: muestra la variable MAC.
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	31/03/2009

source $(dirname $0)/hidraEnviron

echo $MAC
