#!/bin/bash
# Nombre:	hidraUpdateCache
# Descripcion:	Copia una imagen del repositorio al cache local.
# Formato:	hidraUpdateCache iprepo dirbase imagen
#		El fichero imagen tiene el formato:
#			nombre.compresor-numparticion[.metodotransferencia]
# Salida:	(por determinar)
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
#		3 - tipo de particion desconocido o no se puede montar.
# Requisitos:	hidraDisk, RestoreImageFromPartition (EAC)
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatible con EAC: llama a la funcion RestorePartitionFromImage 
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	27/03/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 3 parametros.
[ $# -ne 3 ] && exit 1

# NOTAS: no se comprueba previamente el tipo de particion,
#	 la funcion RestorePartitionFromImage no devuelve errores.
UpdateCache $1 "${2%/}/" "$3"

