#!/bin/bash
# Nombre:	hidraIsLocked
# Descripcion:	Indica si existe el fichero de bloqueo para una particion en uso exlusivo.
# Formato:	hidraIsLocked numdisco numparticion
# Salida:	(ninguna)
# Codigo salida:0 - sin bloquear
#		1 - bloqueada
# Requisitos:	hidraDisk
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatibilidad Con EAC: llama a la funcion MountPartition.
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	14/05/2009

source $(dirname $0)/hidraEnviron

# Sustituye num. de disco por el dispositivo.
PART="$(hidraDisk $1 $2)" || exit

test -f /var/lock/lock${PART//\//-}

