#!/bin/bash
# Nombre:       CaminoWindows
# Descripcion:  Traduce a Linux el camino completo de un fichero Windows
#		(sin contar mayusculas ni minusculas) o de un repositorio.
# Formatos:     hidraPath fichero
#               hidraPath iprepo fichero
#               hidraPath numdisco numparticion fichero
# Salida:       Cadena con el camino del fichero en Linux.
# Error:        1 - mal formato de ejecución.
#		2 - no existe el fichero.
# Requisitos:   grep, sed, hidraDisk, ConnectToRepo (EAC)
# Notas:        Solo ejecutable por root
#		La particion de Windows debe estar montada previamente.
# Version:      1.0 - Version inicial.
# Autor:        Ramon Gomez - ETSII, Univ. Sevilla
# Fecha:        21/05/2008
# Version:      1.1 - 3 formatos de ejecucion.
# Autor:        Ramon Gomez - ETSII, Univ. Sevilla
# Fecha:        19/05/2009


source $(dirname $0)/hidraEnviron

# Proceso dependiendo del numero de parametros.
case $# in
    1)	FICH="$1" ;;
    2)	FICH=$(ConnectToRepo $1 / "$2") ;;
    3)	FICH="$(hidraMount $1 $2)/$3" || exit $ERRNOTFOUND ;;
    *)	exit $ERRFORMAT ;;
esac

# Eliminar "/" duplicados y quitar los "/" inicial y final.
FICH="$(echo $FICH|sed -e 's/\(\/\)*\1/\//g' -e 's/^\///' -e 's/\/$//')"
FICHANT=""
CAMINO="/"
while [ "$FICH" != "$FICHANT" ]; do
    # Busca el nombre correcto en el directorio actual.
    cd "$CAMINO"
    CAMINO="${CAMINO}/$(ls -A | grep -i -m1 "^${FICH%%/*}$")" || exit $ERRNOTFOUND
    FICHANT="$FICH"
    FICH="${FICH#*/}"
done

# Muestra el camino Linux, quitando el "/" inicial duplicado.
[ "$CAMINO" != "/" ] && echo ${CAMINO#/}

