#!/bin/bash
# Nombre:	hidraMount
# Descripcion:	Monta una particion segun su tipo definido en la tabla del disco.
# Formato:	hidraMount numdisco numparticion
# Salida:	Directorio del punto de montaje.
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
#		3 - tipo de particion desconocido o no se puede montar.
# Requisitos:	hidraDisk, MountPartition (EAC)
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatibilidad Con EAC: llama a la funcion MountPartition.
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	25/03/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 2 parametros.
[ $# -ne 2 ] && exit $ERRFORMAT

# Error si la particion esta bloqueada.
hidraIsLocked $1 $2 && exit $ERRLOCKED

# Sustituye num. de disco por el dispositivo.
PART="$(hidraDisk $1 $2)" || exit $?

# NOTAS: no se comprueba previamente el tipo de particion,
#	 la funcion MountPartition no devuelve errores.
MONT=$(MountPartition $* 2>/dev/null)
# Error si la salida tiene mas de 1 palabra ( ), no se ha montado la particion.
[ -z "${MONT/* *}" ] && exit $ERRPARTITION
echo $MONT

