#!/bin/bash
# Nombre:	hidraEnviron
# Descripcion:	Define las variables del entorno de trabajo de Hidra.
# Formato:	source hidraEnviron
# Notas:	Solo ejecutable por root
# Licencia:	GNU GPL
# Version:	1.0 - Version inicial compatible con EAC
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	26/03/2009

# Directorios de EAC y de HIDRA.
REPO=${REPO:-"/var/EAC"}
HIDRADIR=${HIDRADIR:-"$REPO/hidra"}

# Funciones EAC
if ! typeset -F Disk; then
    if [ -d $REPO/admin/librerias ]; then
	for i in $REPO/admin/librerias/*.lib; do
	    source $i
	done
	[ -z "$(echo $PATH|grep $REPO/admin)" ] && PATH=$PATH:$REPO/admin/procedimientos
    fi
fi
# Caminos de busqueda de comando.
[ -z "$(echo $PATH|grep $HIDRADIR)" ] && PATH=$PATH:$HIDRADIR/scripts
export PATH HIDRADIR
