#!/bin/bash
# Nombre:	hidraReboot
# Descripcion:	Reinicia el ordenador cliente.
# Formato:	hidraReboot
# Salida:	Ninguna (por determinar).
# Error:	Ninguno (por determinar).
# Requisitos:	reboot
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatibilidad Con EAC: apagado Linux.
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	02/04/2009

reboot
