#!/bin/bash
# Nombre:	hidraRestorePartitionFromImage
# Descripcion:	Crea una imagen completa de una particion de disco.
# Formato:	hidraRestorePartitionFromImage numdisco numparticion iprepo dirbase imagen
#		El fichero imagen tiene el formato:
#			nombre.compresor-numparticion[.metodotransferencia]
# Salida:	(por determinar)
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
#		3 - tipo de particion desconocido o no se puede montar.
# Requisitos:	hidraDisk hidraFSExtend, RestoreImageFromPartition (EAC)
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatible con EAC: llama a la funcion RestorePartitionFromImage 
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	27/04/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 5 parametros.
[ $# -ne 5 ] && exit $ERRFORMAT

# Sustituye num. de disco por el dispositivo.
PART="$(hidraDisk $1 $2)" || exit $?
# Error si no existe el fichero de imagen.
FICH=$(ConnectToRepo "$3" "${4%/}/" "$5")
[ -f "$FICH" ] || exit $ERRNOTFOUND
# Error si la imagen no cabe en la particion.
[ $(hidraImageSize "$3" "$4" "$5") > $(hidraPartitionSize $1 $2) ] && exit $ERRPARTITION

# NOTAS: no se comprueba previamente el tipo de particion,
#	 la funcion RestorePartitionFromImage no devuelve errores.
RestorePartitionFromImage $1 $2 $3 "${4%/}/" "$5"
# Extender el sistema de archivos al tamano de la particion.
hidraFSExtend $1 $2
