#!/bin/bash
# Nombre:       hidraGetWindwosName
# Descripcion:  Muestra el nombre del equipo en el registro de Windows.
# Formato:      hidraGetWindowsName ndisco nparticion
# Salida:       nombre
# Error:        1 - mal formato de ejecución.
#               2 - no existe el fichero de dispositivo.
#		3 - fallo al montar la particion		
# Requisitos:   hidraMount, hidraGetRegistryKey
# Notas:        Solo ejecutable por root
# Version:      1.0 - Compatible con EAC: nueva funcion.
# Autor:        Ramon Gomez - ETSII, Univ. Sevilla
# Fecha:        23/04/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 2 parametros.
[ $# != 2 ] && exit $ERRFORMAT

# Montar particion.
DIRMONT=$(hidraMount $1 $2) || exit $?

trap "hidraUnmount $DIRMONT" 1 2 3 6

# Obtener valor de la clave de registro.
hidraGetRegistryKey $DIRMONT system '\ControlSet001\Control\ComputerName\ComputerName\ComputerName'

