#!/bin/bash
# Nombre:	hidraLock
# Descripcion:	Genera un fichero de bloqueo para una particion en uso exlusivo.
# Formato:	hidraLock numdisco numparticion
# Salida:	(ninguna)
# 		Genera un fichero /var/lock/lock-dev-numparticion
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
# Requisitos:	hidraDisk
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatibilidad Con EAC: llama a la funcion MountPartition.
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	14/05/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 2 parametros.
[ $# -ne 2 ] && exit $ERRFORMAT

# Sustituye num. de disco por el dispositivo.
PART="$(hidraDisk $1 $2)" || exit $?

touch /var/lock/lock${PART//\//-}

