#!/bin/bash
# Nombre:	hidraBoot
# Descripcion:	Arranca el sistema operativo de la particion indicada.
# Formato:	hidraBoot numdisco numparticion
# Salida:	Directorio del punto de montaje.
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
#		3 - tipo de particion desconocido o no se puede montar.
#		5 - sin sistema operativo.
# Requisitos:	hidraDisk, hidraTypeFS, hidraOSVersion,
#		hidraLinuxBootParameters,  HDBoot (EAC)
# Notas:	Solo ejecutable por root
# Version:	1.0 - Compatibilidad Con EAC:
#			Para Windows: llama a la funcion HDBoot.
#			Para Linux: soluciona el problema de HDBoot.
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	01/04/2009

source $(dirname $0)/hidraEnviron

# Error si no se reciben 2 parametros.
[ $# -ne 2 ] && exit $ERRFORMAT

# Obtiene el tipo de particion y montarla.
TIPO="$(hidraTypeFS $1 $2)" || exit $?
# Montar la particion.
MONT=$(hidraMount $1 $2) || exit $?

case "$TIPO" in
     NTFS|HNTFS|FAT32|HFAT32)
	# Arranque Windows.
	# Compruebar si hay un SO definido antes de arrancar.
	[ -z "$(hidraOSVersion $1 $2)" ] && exit $ERRNOTOS
	cp $REPO/admin/gestion/grub/* $MONT
	# Configurar GRUB4DOS
	kexec -l $MONT/grub.exe --append=--config-file="find --set-root /ntldr; chainloader /ntldr"
	;;
     EXT[234]|REISERFS|REISER4)
	# Obtiene los parametros de arranque.
	PARAMS=$(hidraLinuxBootParameters $1 $2) || exit $?
	read -e KERNEL INITRD APPEND <<<"$PARAMS"
	# Si no hay kernel, no hay sistema operativo.
	[ -z "$KERNEL" ] && exit $ERRNOTOS
	# Configurar kernel Linux con los parametros leidos de su GRUB.
	kexec -l ${MONT}${KERNEL} --append="$APPEND" --initrd=${MONT}${INITRD}
	;;
     *) exit $ERRPARTITION
	;;
esac

# Arrancar.
kexec -e
