#!/bin/bash
# Nombre:	hidraUnmountAll
# Descripcion:	Desmonta todos los sitemas de archivos de un disco.
# Formato:	hidraUnmountAll numdisco
# Salida:	Ninguna (por determinar)
# Error:	1 - formato incorrecto.
#		2 - disco no detectado (no corresponde con un dispositivo).
# Requisitos:	hidraDisk, hidraUnmount
# Notas:	Solo ejecutable por root
# Version:	1.0 - Nueva funcion.
# Autor:	Ramon Gomez, ETSII Univ. Sevilla
# Fecha:	26/05/2009

source $(dirname $0)/hidraEnviron

# Error si no se recibe 1 parametro
[ $# -ne 1 ] && exit $ERRFORMAT

# Sustituye num. de disco por el dispositivo.
DISCO="$(hidraDisk $1)" || exit $?

# Para cada particion del disco, llamar a la funcion de desmontar.
for PART in ${DISCO}[1-9]; do
    hidraUnmount $1 ${PART#$DISCO}
done
# No se devuelve codigo de error.
exit 0
