#!/bin/sh

# Simple hack to wait for systray to be present
# Exec tool if not already runned by session manager
ps -ef | grep "$USER" | grep -v grep | grep -v OGAgentTool-startup | grep 'OGAgentTool' -q
# If not already running
if [ $? -eq 1 ]; then
    sleep 5
    exec /usr/bin/OGAgentTool
fi