#!/bin/bash
PARM=`cat`

BASEDIR=/opt/opengnsys
REPONAME=ogAdmRepo
REPOLOG=$BASEDIR/log/$REPONAME.log


PARM1=$(echo $PARM | cut -f1 -d" ")
PARM2=$(echo $PARM | cut -f2 -d" ")
PARM3=$(echo $PARM | cut -f3 -d" ")
PARM4=$(echo $PARM | cut -f4 -d" ")


case $PARM1 in
	START_MULTICAST)
		#1 START_MULTICAST
		#2 fichero a enviar
		#3 opciones de multicast
		FILE=/opt/opengnsys/images$PARM2
		MCASTOPT=$PARM3
		echo "/opt/opengnsys/bin/sendFileMcast $FILE $MCASTOPT" >> $REPOLOG
		/opt/opengnsys/bin/sendFileMcast $FILE $MCASTOPT >> $REPOLOG
	;;
esac