#!/bin/bash
# Script para solicitar acciones al servidor de administración desde los clientes. 
# Acciones permitidas: configurar modo de arranque.
PARM=`cat`



BASEDIR=/opt/opengnsys
PATH=$PATH:$BASEDIR/bin
SERVERNAME=ogAdmServer
SERVERLOG=$BASEDIR/log/$SERVERNAME.log


# Añade registro de incidencias.
function echolog () {
	date +"%Y%m%d-%H%M%S $*" >> $SERVERLOG
}


PARM1=$(echo $PARM | cut -f1 -d" ")
PARM2=$(echo $PARM | cut -f2 -d" ")
PARM3=$(echo $PARM | cut -f3 -d" ")
PARM4=$(echo $PARM | cut -f4 -d" ")


case "$PARM1" in
	SET_CLIENTMODE)
		#1 SET_CLIENTMODE
		#2  template
		#3 pc_name o group_pc
#4 modo temporal o permanente

		TEMPLATE="$PARM2"
		PC="$PARM3"
#incluyo parametro de MODO
		MODO="$PARM4"
		echolog "Ejecutar $(which setclientmode) $FILE $MCASTOPT"
#incluyo parametro de MODO
		setclientmode $TEMPLATE $PC $MODO &>> $SERVERLOG
		exit $? 
	;;
	default)
	    echolog "Solicitud con parametros  \"$PARM\"  no realizada, no registrada o con errores"
	;;
esac

