#! /bin/sh

case $1 in
prereqs)
	exit 0
	;;
esac

if [ "$ROOTFSTYPE" = ntfs ] || [ "$ROOTFSTYPE" = ntfs-3g ] || \
   [ "$LOOPFSTYPE" = ntfs ] || [ "$LOOPFSTYPE" = ntfs-3g ]; then
	   mkdir -p /dev/.initramfs/varrun
	pidof mount.ntfs >> /dev/.initramfs/varrun/sendsigs.omit
	pidof mount.ntfs-3g >> /dev/.initramfs/varrun/sendsigs.omit
fi

exit 0
