#!/bin/bash
############################################################
######Servidor de images torrent EAC  v0.0.7r4 para Advanced Deploy enViorenment###########
# Liberado bajo licencia GPL <http://www.gnu.org/licenses/gpl.html>################
############## 2008 Antonio Doblas Viso adv@uma.es ##########################
############ Universidad de Malaga (Spain)############################
###########################################################

case $1 in 
	status)
		ps aux | grep ctorrent | grep -v grep | awk  -F: '{print $3}'
		;;
	start)
		ctcs -d 5000 -u 5000 &
		#for i in `find /var/EAC/hdimages/ -name "*torrent"`
		#do
		#nice -n 8 ctorrent $i -d
		#done
	;;
	restart)
		for p in `ps aux | grep ctorrent | grep -v grep | awk '{print $2}'`
		do
		kill -9 $p
		done
		#for i in `find /var/EAC/hdimages/ -name "*torrent"`
		#do
		#nice -n 8 ctorrent $i -d
		#done
		;;
	stop)
		for p in `ps aux | grep ctorrent | grep -v grep | awk '{print $2}'`
		do
		kill -9 $p
		done
		;;		
	*)
        echo "Usage (start|stop|restart|status)"
	;; 
esac 
exit 0
	
		
	
