#!/bin/sh 
###########################################################
#####Servidor EAC  v0.0.7 para Advanced Deploy enViorenment###########
# Liberado bajo licencia GPL <http://www.gnu.org/licenses/gpl.html>################
############# 2008 Juan Antonio LLamas Mantecón ##########################
########### Universidad de Malaga (Spain)############################
##########################################################

case $1 in 
status)
 ps aux | grep bttrack | grep -v grep | awk -F: '{print $3}'
;;
start)
        bttrack --reannounce_interval 10 --port 1234 --dfile /root/dstate --logfile /root/bttracker.log &
	 ps aux | grep bttrack | grep -v grep | awk -F: '{print $3}'
;; 
stop)
        pkill bttrack
;; 
restart)
        pkill bttrack
        sleep 2
        bttrack --reannounce_interval 60 --port 1234 --dfile /root/dstate --logfile /root/bttracker.log &
	 ps aux | grep bttrack | grep -v grep | awk -F: '{print $3}'
;; 
*)
        echo "Usage (start|stop|restart|status)"
;; 
esac 
exit 0
