#!/usr/bin/php
<?
require("/var/EAC/admin/config/parametrosaccesoBD.php");
require_once("/var/EAC/admin/config/parametrosaccesoBD.php");

# formato de entrada 
# 1IP ; 2tiempo proceso; 3comando; 4parametros 
$hora=date("H:i:s");
$dia=date("Y-m-d");
#formato del log


# IPsolicitante ; dia ; hora ; tiempo proceso ; comando; parametros
#formato del log


#mensaje en ventana del solicitante.
#echo($_SERVER['argv'][1]  . " ; " . $dia . " ; " . $hora . " ; "  . $_SERVER['argv'][2] . " ; "  . $_SERVER['argv'][3] . " ; "  . $_SERVER['argv'][4]);
$info=$_SERVER['argv'][1]  . " ; " . $dia . " ; " . $hora . " ; "  . $_SERVER['argv'][2] . " ; "  . $_SERVER['argv'][3] . " ; "  . $_SERVER['argv'][4] . "\n";
echo($info);




## escritura en el ficheor /var/EAC/hosts/$IP-Log
$fp = fopen(REPO . "hosts/" . $_SERVER['argv'][1] ."-Log", "ab");
fwrite($fp, $info);
fclose($fp);


## insertar la informacion en la base de datos
$conexion=mysql_connect(SQL_HOST, SQL_USER, SQL_PASS) or die ('no se ha podido conectar con mysql');

mysql_select_db(DATABASE, $conexion);
$insert="insert into log (ip, dia, hora, tiempo_proceso, comando, parametros) values ('".$_SERVER['argv'][1] . "','" . $dia . "','" .$hora . "','" .$_SERVER['argv'][2]."','".$_SERVER['argv'][3]."','".$_SERVER['argv'][4]."')";
#echo $insert . "\n";
$resultado = mysql_query($insert) or die (mysql_error());
mysql_close($conexion);

?>