#!/usr/bin/env sh

# Directories
SRCDIR=$(dirname "$0")
BINDIR=/usr/local/bin
INITDIR=/Library/LaunchDaemons

# Dependencies:
#easy_install pip
#pip install netifaces requests six

# Copy files.
cp $SRCDIR/ogagent $BINDIR
cp $SRCDIR/es.opengnsys.ogagent.plist $INITDIR

# Show post-installation message.
#osascript -e 'display notification "You must install following Python modules: netifaces, requests, six." with title "OGAgent Installer'

