#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          ogagent
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OpenGnsys Agent Service
### END INIT INFO
#

# . /lib/lsb/init-functions

case "$1" in
  start|stop|restart) 
    /usr/bin/ogagent $1
	;;
  force-reload)
  	/usr/bin/ogagent restart 
	;;
  *) echo "Usage: $0 {start|stop|restart|force-reload}" >&2; exit 1 ;;
esac

