#!/bin/bash
# Scirpt de ejemplo para arancar un sistema operativo instalado.
# (puede usarse como base para el programa de arranque usado por OpenGNSys Admin).

PROG="$(basename $0)"
if [ $# -ne 2 ]; then
    ogRaiseError $OG_ERR_FORMAT "Formato: $PROG ndisco nparticion"
    exit $?
fi

echo "[0] Inicio del proceso de arranque."
PART=$(ogDiskToDev "$1" "$2") || exit $?
NAME=$(ogGetHostname)
NAME=${NAME:-"pc"}
OSTYPE=$(ogGetOsType $1 $2)

echo "[10] Desmontar todos los sistemas de archivos."
sync
for (( i=1; i <= $(ogDiskToDev | wc -w); i++ )); do
    ogUnmountAll $i 2>/dev/null
done
case "$OSTYPE" in
    Windows)
        echo "[30] Activar particion de Windows $PART."
        ogSetPartitionActive $1 $2
        echo "[40] Comprobar sistema de archivos."
        ogCheckFs $1 $2
        echo "[50] Asignar nombre Windows \"$NAME\" y usuario por defecto."
        ogSetWindowsName $1 $2 "$NAME"
        ogSetWinlogonUser $1 $2 " "
        ;;
    Linux)
        echo "[30] Asignar nombre Linux \"$NAME\"."
        ETC=$(ogGetPath $1 $2 /etc)
        [ -d "$ETC" ] && echo "$NAME" >$ETC/hostname 2>/dev/null
        if [ -f "$ETC/fstab" ]; then
            echo "[50] Actaualizar fstab con particion raiz \"$PART\"."
            awk -v P="$PART " '{ if ($2=="/") {sub(/^.*$/, P, $1)}
                                 print } ' $ETC/fstab >/tmp/fstab
            mv /tmp/fstab $ETC/fstab
        fi
        ;;
esac
echo "[70] Desmontar cache local."
ogUnmountCache
echo "[90] Arrancar sistema operativo."
ogBoot $1 $2

