#!/bin/bash
# Scirpt de ejemplo para almacenear en fichero temporal el listado de software.
# (puede usarse como base para el programa de arranque usado por OpenGNSys Admin).

PROG="$(basename $0)"
if [ $# -ne 2 ]; then
    ogRaiseError $OG_ERR_FORMAT "$MSG_FORMAT: $PROG ndisco nparticion"
    exit $?
fi

# Directorio del servidor donde se exportan los ficheros de registro.
SERVERLOGDIR=$(mount | awk -v d=$OGLOG '
				BEGIN {FS="[: ]"}
				{if ($4==d) dir=$2}
				END {print dir}')
# Fichero de listado:  soft-IP-ndisco-npart
SOFTFILE="soft-$(ogGetIpAddress)-$1-$2"
# Redirigir salida al fichero de listado.
ogListSoftware "$1" "$2" >$OGLOG/$SOFTFILE || exit $?
# Salid: camino del fichero de listado en el servidor de repositorio.
echo $SERVERLOGDIR/$SOFTFILE
