#!/bin/bash
# Scirpt de ejemplo para reiniciar un ordenador
# (puede usarse como base para el programa de reinicio usado por OpenGNSys Admin).

PROG="$(basename $0)"

echo "[10] Desmontar todos los sistemas de archivos."
sync
for (( i=1; i <= $(ogDiskToDev | wc -w); i++ )); do
    ogUnmountAll $i 2>/dev/null
done
echo "[50] Desmontar cache local."
ogUnmountCache
echo "[90] Reiniciar el equipo."
/sbin/reboot

