<?php

/*
 * This file is part of the Opengnsys Project package.
 *
 * Created by Miguel Angel de Vega Alcantara on 01/10/18. <miguelangel.devega@sic.uhu.es>
 * Copyright (c) 2015 Opengnsys. All rights reserved.
 *
 */

namespace Opengnsys\ServerBundle\Repository;

use Opengnsys\CoreBundle\Repository\BaseRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends BaseRepository
{
    public function findByObservable($term = "", $limit = null, $offset = null, $ordered = array(), $selects = array(), $searchs = array(), $matching = array())
    {
        $qb = $this->createQueryBuilder('o');

        if(count($selects) > 0){
            $qb = $this->createSelect($qb, $selects);
        }else{
            $qb->select("DISTINCT o.createdAt, o.updatedAt, o.notes, o.description, o.idurlimg, o.title, o.publicxcoordinate, o.publicycoordinate, o.publicmode, o.privatexcoordinate, o.privateycoordinate, o.privatemode, o.comments, o.publicmenuhtml, o.privatemenuhtml, o.resolution, o.id");
        }

        if($term != ""){
            if(count($searchs) > 0){
                $qb = $this->createSearch($qb, $term, $searchs);
            }else{
                $qb->andWhere("o.createdAt LIKE :term OR o.updatedAt LIKE :term OR o.notes LIKE :term OR o.description LIKE :term OR o.idurlimg LIKE :term OR o.title LIKE :term OR o.publicxcoordinate LIKE :term OR o.publicycoordinate LIKE :term OR o.publicmode LIKE :term OR o.privatexcoordinate LIKE :term OR o.privateycoordinate LIKE :term OR o.privatemode LIKE :term OR o.comments LIKE :term OR o.publicmenuhtml LIKE :term OR o.privatemenuhtml LIKE :term OR o.resolution LIKE :term OR o.id LIKE :term ")->setParameter('term', '%' . $term . '%');
            }
        }

        $qb = $this->createMaching($qb, $matching);

        $qb = $this->createOrdered($qb, $ordered);

        if($limit != null){
            $qb->setMaxResults($limit);
        }

        if($offset){
            $qb->setFirstResult($offset);
        }

        $entities = $qb->getQuery()->getScalarResult();
        return $entities;
    }

    public function countFiltered($term = "", $searchs = array(), $matching = array())
    {
        $qb = $this->createQueryBuilder('o');

        $qb->select("count(DISTINCT o.id)");

        if($term != ""){
            if(count($searchs) > 0){
                $qb = $this->createSearch($qb, $term, $searchs);
            }else{
                $qb->andWhere("o.createdAt LIKE :term OR o.updatedAt LIKE :term OR o.notes LIKE :term OR o.description LIKE :term OR o.idurlimg LIKE :term OR o.title LIKE :term OR o.publicxcoordinate LIKE :term OR o.publicycoordinate LIKE :term OR o.publicmode LIKE :term OR o.privatexcoordinate LIKE :term OR o.privateycoordinate LIKE :term OR o.privatemode LIKE :term OR o.comments LIKE :term OR o.publicmenuhtml LIKE :term OR o.privatemenuhtml LIKE :term OR o.resolution LIKE :term OR o.id LIKE :term ")->setParameter('term', '%' . $term . '%');
            }
        }

        $qb = $this->createMaching($qb, $matching);

        $count = $qb->getQuery()->getSingleScalarResult();
        return $count;
    }
}
