#!/bin/bash

#/**
#         configureOS
#@brief   Scirpt de ejemplo para realizar la configuracion del sistema operativo restaurado.
#@brief (puede usarse como base para el programa de creación de imágenes usado por OpenGnSys Admin).
#@param 1 disco 
#@param 2 particion 
#@return  
#@TODO  comprobar que el tipo de particion corresponde con el sistema de archivos.
#@exception OG_ERR_FORMAT     # 1 formato incorrecto.
#@version 1.0.1 - Integracion cambio de nombre, extender fs, chequear particion activa
#@author  
#@date   2011-05-11
#@version 1.0.1 - Configura el sector de la particion y el gestor de windows para iniciarse desde cualquier particion.  
#@author Antonio J. Doblas Viso.    Universidad de Malaga.
#@date   2011-05-20
#@version 1.0.2 - Configura el sector de la particion y el gestor de linux para iniciarse desde cualquier particion.  
#@author Antonio J. Doblas Viso.    Universidad de Malaga.
#@date   2011-11-22



# Si el sistema de archivos no esta extendido. Realizar.
PARTSIZE=$(ogGetPartitionSize $1 $2)
FSSIZE=$(ogGetFsSize $1 $2)
if [ $FSSIZE -lt $PARTSIZE ]; then
	echo "Extender sistema de archivos."
	ogExtendFs $1 $2
fi

#Si no existe particion activa, activar este sistema.
FLAGACTIVE=$(ogGetPartitionActive $1)
[ -z $FLAGACTIVE ] && ogSetPartitionActive $1 $2

# Cambiar nombre en sistemas Windows y quitar usuario de acceso por defecto.
if [ "$(ogGetOsType $1 $2)" = "Windows" ]; then
    # Cambiar nombre en sistemas Windows.
    HOST=$(ogGetHostname)
    HOST=${HOST:-"pc"}
    ogSetWindowsName $1 $2 "$HOST"
    # Descomentar la siguiente línea para cambiar usuario de inicio.
    #ogSetWinlogonUser $1 $2 " "
    # Configurar el boot sector de la partición Windows.
    ogFixBootSector $1 $2
    # Configurar el gestor de arranque de Windows XP/Vista/7.
    ogWindowsBootParameters $1 $2
    # Registrar en Windows que la partición indicada es su nueva unidad C:\
    ogWindowsRegisterPartition $1 $2 C $1 $2
    ogLoadHiveWindows $1 $2; ogSetWindowsChkdisk $OGWINCHKDISK; ogUpdateHiveWindows
fi

if [ "$(ogGetOsType $1 $2)" = "Linux" ]; then
	ogGrubInstallPartition $1 $2
fi