#!/bin/bash
# Scirpt de ejemplo para devolver el listado de hardware.
# Nota: se usa como base para el programa de recogida de listado de hardware de OpenGnsys Admin.
# Formato:  listHardwareInfo 

PROG=$(basename "$0")
if [ $# -ne 0 ]; then
    ogRaiseError $OG_ERR_FORMAT "$MSG_FORMAT: $PROG "
    exit $?
fi

# Mostrar inventario (líneas con formato: Clave=Valor).
ogListHardwareInfo
