#!/bin/bash
# Scirpt de ejemplo para almacenear en fichero temporal el listado de software.
# Nota: se usa como base para el programa de recogida de listado de software de OpenGnsys Admin.
# Formato:  listSoftwareInfo [-r] ndisk npart
#		-r   listado reducido (sin parches de Windows)

PROG=$(basename "$0")
REDUCED="no"
if [ "$1" = "-r" ]; then
    REDUCED="yes"
    shift
fi
if [ $# -ne 2 ]; then
    ogRaiseError $OG_ERR_FORMAT "$MSG_FORMAT: $PROG ndisco nparticion"
    exit $?
fi

# Mostrar inventario (líneas con formato: Programa Versión).
if [ "$REDUCED" = "no" ]; then
    ogListSoftware "$1" "$2" || exit $?
else
    ogListSoftware "$1" "$2" | egrep -v "\(KB[0-9]{6}\)" || exit $?
fi

