#!/bin/bash
# Scirpt de ejemplo para apagar un ordenador
# (puede usarse como base para el programa de apagado usado por OpenGNSys Admin).


# Desmontar los sistemas de archivos y la caché local.
echo "[10] Desmontar todos los sistemas de archivos."
sync
for (( i=1; i <= $(ogDiskToDev | wc -w); i++ )); do
    ogUnmountAll $i 2>/dev/null
done
echo "[50] Desmontar cache local."
ogUnmountCache 2>/dev/null
echo "[70] Apagando el equipo."
# Estado correcto de Wake-On-Lan antes de apagar.
ethtool -s $DEVICE wol g 2>/dev/null
# Detectar Busybox.
BUSYBOX=$(which busyboxOLD)
BUSYBOX=${BUSYBOX:-"busybox"}
(sleep 5 && $BUSYBOX poweroff)


